FROM node:20-alpine

WORKDIR /app

COPY client/package*.json ./client/
WORKDIR /app
RUN npm ci --prefix ./client

WORKDIR /app
COPY client ./client

EXPOSE 5173

CMD ["npm", "dev", "--prefix", "./client"]