FROM node:20-alpine

WORKDIR /app

COPY server/package*.json ./server/
WORKDIR /app
RUN npm ci --prefix ./server

WORKDIR /app
COPY server ./server

EXPOSE 3001

CMD ["npm", "start", "--prefix", "./server"]